services:
  angular:
    image: angular
    ports: 
      - "4200:4200"
  spring-boot-app:
    image: devopsangular
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/demo
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - spring.jpa.hibernate.ddl-auto=update
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'demo'
      MYSQL_ROOT_USERNAME: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3308:3306"
    volumes:
      - demo:/var/lib/mysql
volumes:
    demo:


